config/routes.rb
Rails.application.routes.draw do
  get "/stocktwits" => "api_vendors#stocktwits_auth"
  get "/stocktwits/code" => "api_vendors#stocktwits_code"

  resources :api_vendors

  resources :users

end

app/models/api_vendor.rb
class ApiVendor < ActiveRecord::Base
end

app/models/stock_twit.rb
class StockTwit < ActiveRecord::Base
  require 'oauth2'
  include HTTParty
  base_uri 'https://api.stocktwits.com'
  default_options.update(verify: false)


  def initialize(client_id, client_secret)
    @client_id = client_id
    @client_secret = client_secret
    @base_uri = 'https://api.stocktwits.com'
  end

  #get the code
  def auth_redirect_url
    #self.class.get "/api/2/oauth/authorize", query: @auth_options
    client = OAuth2::Client.new(
      @client_id,
      @client_secret,
      :site => @base_uri,
      :authorize_url => "/api/2/oauth/authorize",
      :ssl => {:verify => false}
    )
    client.auth_code.authorize_url(:redirect_uri => 'http://localhost:3000/stocktwits/code')
  end

  def auth_receive_code code
    self.class.post("/api/2/oauth/token?client_id=#{@client_id}&client_secret=#{@client_secret}&code=#{code}&grant_type=authorization_code&redirect_uri=http://localhost:3000/stocktwits/success")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/api_vendors_controller.rb
class ApiVendorsController < ApplicationController
  before_action :set_api_vendor, only: [:show, :edit, :update, :destroy]

  # GET /api_vendors
  # GET /api_vendors.json
  def index
    @api_vendors = ApiVendor.all
  end

  # GET /api_vendors/1
  # GET /api_vendors/1.json
  def show
  end

  def stocktwits_auth
    vendor = ApiVendor.find_by name: "stocktwits"
    stocktwits = StockTwit.new(vendor.client_id, vendor.client_secret)
    @auth_url = stocktwits.auth_redirect_url
=begin
    respond_to do |format|
      format.html { redirect_to @auth_url }
    end
=end
  end

  def stocktwits_code
    @code = params[:code]
    #TODO: Cleanup with before filter
    vendor = ApiVendor.find_by name: "stocktwits"
    stocktwits = StockTwit.new(vendor.client_id, vendor.client_secret)
    @access_token = stocktwits.auth_receive_code @code
  end

  # GET /api_vendors/new
  def new
    @api_vendor = ApiVendor.new
  end

  # GET /api_vendors/1/edit
  def edit
  end

  # POST /api_vendors
  # POST /api_vendors.json
  def create
    @api_vendor = ApiVendor.new(api_vendor_params)

    respond_to do |format|
      if @api_vendor.save
        format.html { redirect_to @api_vendor, notice: 'Api vendor was successfully created.' }
        format.json { render :show, status: :created, location: @api_vendor }
      else
        format.html { render :new }
        format.json { render json: @api_vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_vendors/1
  # PATCH/PUT /api_vendors/1.json
  def update
    respond_to do |format|
      if @api_vendor.update(api_vendor_params)
        format.html { redirect_to @api_vendor, notice: 'Api vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_vendor }
      else
        format.html { render :edit }
        format.json { render json: @api_vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_vendors/1
  # DELETE /api_vendors/1.json
  def destroy
    @api_vendor.destroy
    respond_to do |format|
      format.html { redirect_to api_vendors_url, notice: 'Api vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_vendor
      @api_vendor = ApiVendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_vendor_params
      params.require(:api_vendor).permit(:name, :client_id, :client_secret)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/api_vendors_helper.rb
module ApiVendorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/api_vendors/_form.html.erb
<%= form_for(@api_vendor) do |f| %>
  <% if @api_vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_vendor.errors.count, "error") %> prohibited this api_vendor from being saved:</h2>

      <ul>
      <% @api_vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Client ID" %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :client_secret %><br>
    <%= f.text_field :client_secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/api_vendors/edit.html.erb
<h1>Editing Api Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @api_vendor %> |
<%= link_to 'Back', api_vendors_path %>

app/views/api_vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Api Vendors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Client ID</th>
      <th>Client secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @api_vendors.each do |api_vendor| %>
      <tr>
        <td><%= api_vendor.name %></td>
        <td><%= api_vendor.client_id %></td>
        <td><%= api_vendor.client_secret %></td>
        <td><%= link_to 'Show', api_vendor %></td>
        <td><%= link_to 'Edit', edit_api_vendor_path(api_vendor) %></td>
        <td><%= link_to 'Destroy', api_vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api vendor', new_api_vendor_path %>

app/views/api_vendors/new.html.erb
<h1>New Api Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', api_vendors_path %>

app/views/api_vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @api_vendor.client_id %>
</p>

<p>
  <strong>Client secret:</strong>
  <%= @api_vendor.client_secret %>
</p>

<%= link_to 'Edit', edit_api_vendor_path(@api_vendor) %> |
<%= link_to 'Back', api_vendors_path %>

app/views/api_vendors/stocktwits_auth.html.erb
<!-- not used -->
<%= link_to "Click here", @auth_url %>

app/views/api_vendors/stocktwits_code.html.erb
<%= @access_token %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I4c</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!-- #TODO Explain Index -->

<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>